name: 'Write Env'
description:
  'Write env file from provided json. Can be used with github secrets or
  variables'
author: 'yoonsoo.kim@kakekomu.com'

inputs:
  env:
    description: 'Output env file path'
    required: true
  json:
    description: 'Json string to write to env file'
    required: true
  regex:
    description: 'Regex to filter out keys'
    required: false

runs:
  using: node20
  main: dist/index.js
