name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    environment:
      name: devtest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test generate secrets
        id: test-action-secrets
        uses: ./
        with:
          env: .env
          json: ${{ toJson(secrets) }}
          regex: 'SECRET_.*'

      - name: Test print
        run: cat .env

      - name: Test generate vars
        id: test-action-vars
        uses: ./
        with:
          env: .env
          json: ${{ toJson(vars) }}

      - name: Test print 2
        run: cat .env
